import { MonthlyNarrativeCard, TrendCard } from '@/components/dashboard/InsightCard'
import { AnomalyAlert } from '@/components/dashboard/AnomalyAlert'
import { Sparkles } from 'lucide-react'
import type { InsightsData } from '@/types/transaction'

async function getData(): Promise<InsightsData> {
  try {
    const base = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'
    const res = await fetch(`${base}/api/insights`, { cache: 'no-store' })
    return res.json()
  } catch {
    return { generated_at: '', monthly: [], anomalies: [], trends: [], investments: [] }
  }
}

export default async function InsightsPage() {
  const insights = await getData()

  const hasContent =
    insights.anomalies?.length > 0 ||
    insights.trends?.length > 0 ||
    insights.monthly?.length > 0 ||
    insights.investments?.length > 0

  return (
    <div className="p-4 md:p-6 space-y-8">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">AI Insights</h1>
        <p className="text-sm text-muted-foreground mt-1">
          {insights.generated_at
            ? `Last updated ${new Date(insights.generated_at).toLocaleDateString()}`
            : 'Generated by Claude Code from your transaction data'}
        </p>
      </div>

      {!hasContent && (
        <div className="flex flex-col items-center justify-center py-24 text-center space-y-3">
          <div className="p-4 bg-muted/30 rounded-full">
            <Sparkles className="h-8 w-8 text-muted-foreground" />
          </div>
          <p className="text-muted-foreground text-sm max-w-xs">
            No insights yet. Update your transactions and run Claude Code to generate insights.
          </p>
        </div>
      )}

      {insights.anomalies?.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-widest">Anomalies</h2>
          <div className="space-y-2">
            {insights.anomalies.map((a, i) => <AnomalyAlert key={i} anomaly={a} />)}
          </div>
        </section>
      )}

      {insights.trends?.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-widest">Trends</h2>
          <div className="grid sm:grid-cols-2 gap-3">
            {insights.trends.map((t, i) => <TrendCard key={i} trend={t} />)}
          </div>
        </section>
      )}

      {insights.monthly?.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-widest">Monthly Summaries</h2>
          <div className="grid sm:grid-cols-2 gap-4">
            {[...insights.monthly].reverse().map((m, i) => <MonthlyNarrativeCard key={i} insight={m} />)}
          </div>
        </section>
      )}

      {insights.investments?.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-widest">Investment Commentary</h2>
          <div className="space-y-3">
            {insights.investments.map((inv, i) => (
              <div key={i} className="rounded-xl border border-border/50 bg-card/50 p-4">
                <p className="text-sm font-bold text-primary">{inv.ticker}</p>
                <p className="text-sm text-muted-foreground mt-1 leading-relaxed">{inv.commentary}</p>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  )
}
