import { RefreshButton } from '@/components/dashboard/RefreshButton'
import { MonthlyNarrativeCard, TrendCard } from '@/components/dashboard/InsightCard'
import { AnomalyAlert } from '@/components/dashboard/AnomalyAlert'
import { Sparkles } from 'lucide-react'
import { getInsights } from '@/lib/data'

export default async function InsightsPage() {
  const insights = await getInsights()

  const hasContent =
    insights.anomalies?.length > 0 ||
    insights.trends?.length > 0 ||
    insights.monthly?.length > 0 ||
    insights.investments?.length > 0

  return (
    <div className="p-4 md:p-6 space-y-8">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white">AI Insights</h1>
          <p className="text-xs text-slate-500 mt-1 uppercase tracking-widest">
            {insights.generated_at
              ? `Last updated ${new Date(insights.generated_at).toLocaleDateString()}`
              : 'Generated by Claude Code from your transaction data'}
          </p>
        </div>
        <RefreshButton />
      </div>

      {!hasContent && (
        <div className="flex flex-col items-center justify-center py-24 text-center space-y-3">
          <div className="p-4 bg-muted/30 rounded-full">
            <Sparkles className="h-8 w-8 text-muted-foreground" />
          </div>
          <p className="text-muted-foreground text-sm max-w-xs">
            No insights yet. Update your transactions and run Claude Code to generate insights.
          </p>
        </div>
      )}

      {insights.anomalies?.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-[10px] font-semibold text-slate-500 uppercase tracking-widest">Anomalies</h2>
          <div className="space-y-2">
            {insights.anomalies.map((a, i) => <AnomalyAlert key={i} anomaly={a} />)}
          </div>
        </section>
      )}

      {insights.trends?.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-[10px] font-semibold text-slate-500 uppercase tracking-widest">Trends</h2>
          <div className="grid sm:grid-cols-2 gap-3">
            {insights.trends.map((t, i) => <TrendCard key={i} trend={t} />)}
          </div>
        </section>
      )}

      {insights.monthly?.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-[10px] font-semibold text-slate-500 uppercase tracking-widest">Monthly Summaries</h2>
          <div className="grid sm:grid-cols-2 gap-4">
            {[...insights.monthly].reverse().map((m, i) => <MonthlyNarrativeCard key={i} insight={m} />)}
          </div>
        </section>
      )}

      {insights.investments?.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-[10px] font-semibold text-slate-500 uppercase tracking-widest">Investment Commentary</h2>
          <div className="space-y-3">
            {insights.investments.map((inv, i) => (
              <div key={i} className="glass rounded-2xl p-4">
                <p className="text-sm font-bold text-cyan-400">{inv.ticker}</p>
                <p className="text-sm text-slate-400 mt-1 leading-relaxed">{inv.commentary}</p>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  )
}
